version: "3.9"

x-logging: &default-logging
  options:
    max-size: "10m"
    max-file: "3"
  driver: json-file

networks:
  ai:
    driver: bridge

volumes:
  ollama_data:
  n8n_data:
  qdrant_storage:

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*        
    networks: [ai]

  llama-stack:
    image: llamastack/distribution-ollama:latest
    container_name: llama-stack
    depends_on:
      - ollama
    restart: unless-stopped
    ports:
      - "8080:8080"
    command: >
      --port 8080
      --env INFERENCE_MODEL=llama3.2:3b
      --env OLLAMA_INFERENCE_MODEL=llama3.2:3b
      --env OLLAMA_URL=http://ollama:11434
    networks: [ai]

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks: [ai]
    logging: *default-logging

  # Minimal I/O microservice: POST catalog/user → JSON recommendations
  recommender:
    build:
      context: ./recommender
      dockerfile: Dockerfile
    container_name: recommender
    restart: unless-stopped
    environment:
      - LLAMA_STACK_URL=http://llama-stack:8080/v1/openai
      - MODEL_ID=llama3.2:3b
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=products_poc
    depends_on:
      - llama-stack
    ports:
      - "9000:9000"
    networks: [ai]
    logging: *default-logging
